### ISSUE TITLE
practice 7

### ISSUE THREAD

**Issue by geopimik** [Zillaynain/autoware_mini_practice#7]
- If I run the code using command: roslaunch practice_7 practice_7.launch tfl_detector:=camera
- then after entering destination I will get the following printouts and error message:

```
[[5000051, 2000585, 1255, 1372, 879, 1024], [5000051, 2000225, 1668, 1890, 932, 1210], [5000051, 2001115, 837, 953, 1090, 1234]]
[[5000051, 2000585, 262, 340, 923, 1020], [5000051, 2000225, 521, 670, 953, 1140]]
[ERROR] [1718657673.127233, 1683546391.186276]: bad callback: <bound method SimpleLocalPlanner.detected_objects_callback of <__main__.SimpleLocalPlanner object at 0x7f4ba7144250>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/edgar/aw_mini_pr_github/src/practice_7/nodes/planning/local/simple_local_planner.py", line 238, in detected_objects_callback
    target_velocity=targetVelocity)
UnboundLocalError: local variable 'targetVelocity' referenced before assignment

[[5000051, 2000585, 1250, 1369, 870, 1019], [5000051, 2000225, 1679, 1909, 916, 1207], [5000051, 2001115, 823, 941, 1085, 1232]]
[[5000051, 2000585, 258, 338, 917, 1016], [5000051, 2000225, 526, 681, 943, 1137]]
[[5000051, 2000585, 1245, 1367, 861, 1013], [5000051, 2000225, 1689, 1929, 901, 1203], [5000051, 2001115, 811, 931, 1081, 1231]]
[ERROR] [1718657673.248394, 1683546391.287088]: bad callback: <bound method SimpleLocalPlanner.detected_objects_callback of <__main__.SimpleLocalPlanner object at 0x7f4ba7144250>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/edgar/aw_mini_pr_github/src/practice_7/nodes/planning/local/simple_local_planner.py", line 238, in detected_objects_callback
    target_velocity=targetVelocity)
UnboundLocalError: local variable 'targetVelocity' referenced before assignment

```
These need to be fixed.

**Comment by Zillaynain** [comment]
I think it was because I sent you wrong zip file. Please let me know if there is still problem.

**Comment by Zillaynain** [comment]
Hi Edgar,
If i set the pat then it gives me images and it detects the traffic lights. Also it does not give target velocity error anymore.

**Comment by geopimik** [comment]
OK, I guess I did mix up something here.
